### PR TITLE
Kebab case everything

### PR DESCRIPTION
**Pull request by br3akzero**
I have renamed every file inside of the /src directory to it's kebab case representative. Note that I wasn't able to test if there are any build time errors because I am not able to install the dependencies for this project. @pheeria is responsible for testing at build time if everything is working as before.

### CODE REVIEW

**Comment by pheeria** [comment]
Thanks for the PR! 🎉 

- The code works as intended if one import is fixed:
It should be 
```jsx
import { DragSource } from 'react-dnd'
```
instead of 
```jsx
import { DragSource } from '../field/node_modules/react-dnd'
```
on line 3 of `Player.js`.

- Can you please revert `package.json` to its state on `master`?
- Unfortunately, as mentioned in the issue #9, `git` didn't pick up changes for the names, where only casing was changed.
image

**Comment by br3akzero** [comment]
@pheeria I think these changes should be it.Note that I have reverted all the directory names to their previous ones. If this was unnecessary please say so, so that I could remove the last commit.

**Comment by pheeria** [comment]
> @pheeria I think these changes should be it.Note that I have reverted all the directory names to their previous ones. If this was unnecessary please say so, so that I could remove the last commit.

Sorry, my bad.
I actually meant `package-lock.json`, not `package.json`. Can you please revert it?
As well as your last commit with directory names. The renaming only happened on your machine, since you most probably forgot to use `git mv` commands. However, I can merge the PR after getting `package-lock` back 🙂

**Comment by br3akzero** [comment]
@pheeria third times the charm, hope this one works. I have done as you suggested renaming the files using `git mv` and this time git picked up the changes btw thanks for the tip. Looking forward from hearing from you after you test out the PR.

**Comment by pheeria** [comment]
@Denpex thank you very much, it worked!

**Pull request merged**
